# Generated by Django 5.1.6 on 2026-05-29 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0006_alter_profile_profile_picture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('memorial', 'Memorial'), ('anniversary', 'Anniversary'), ('general', 'General')], default='wedding', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('story', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='campaign_covers')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('goal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='public', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('cohosts', models.ManyToManyField(blank=True, related_name='cohosted_campaigns', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_percent', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='campaigns.campaign')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_links', to='donations.charity')),
            ],
            options={
                'verbose_name_plural': 'Campaign beneficiaries',
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['visibility', 'status'], name='campaigns_c_visibil_9f7031_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['slug'], name='campaigns_c_slug_a60613_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignbeneficiary',
            unique_together={('campaign', 'charity')},
        ),
    ]
