# Generated by Django 5.1.6 on 2025-03-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_charity_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bank_identifier',
        ),
        migrations.AddField(
            model_name='profile',
            name='revolut_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
