# Generated by Django 5.1.6 on 2025-03-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bride_name',
            field=models.CharField(default='Anna', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='groom_name',
            field=models.CharField(default='Alan', max_length=255),
        ),
    ]
