# Generated by Django 5.1.6 on 2025-03-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_remove_profile_bank_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='revolut_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
