# Generated by Django 5.1.6 on 2025-03-10 00:25

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_alter_profile_revolut_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='revolut_username',
            field=models.CharField(default='alanmaizon', max_length=255),
        ),
    ]
