# Generated by Django 5.1.6 on 2025-03-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_charity_logo_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='charity_logos'),
        ),
    ]
