# Generated by Django 5.1.6 on 2026-05-29 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_ledgerentry_payout_payoutaccount_receipt_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
