# Generated by Django 5.1.6 on 2026-05-29 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('donations', '0007_ledgerentry_payout_payoutaccount_receipt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('auto_approved', 'Auto-approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('moderation_score', models.FloatField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='campaigns.campaign')),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='donations.donation')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['campaign', 'moderation_status', 'published_at'], name='messaging_m_campaig_c491c5_idx')],
            },
        ),
    ]
